# Generated by Django 3.2.5 on 2021-08-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0002_deployedtickets_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployedtickets',
            old_name='ticketAddress',
            new_name='sponser',
        ),
        migrations.RemoveField(
            model_name='deployedtickets',
            name='completed',
        ),
    ]
